# Generated by Django 2.1.7 on 2019-03-12 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('casestudy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reaction_time', models.FloatField()),
                ('has_exploded', models.BooleanField(default=False)),
                ('final_conversion', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='casestudy.CaseStudy')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='players.Player')),
            ],
        ),
    ]
