# Generated by Django 2.1.7 on 2019-03-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='case_study',
        ),
        migrations.RemoveField(
            model_name='score',
            name='has_exploded',
        ),
    ]
