# Generated by Django 3.2 on 2021-04-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Votre prénom')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Votre nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Votre adresse e-mail')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'first_name'),
            },
        ),
    ]
