# Generated by Django 2.1.7 on 2019-03-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20190314_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Votre prénom'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Votre nom'),
        ),
    ]
